---
title: all
description: Await many promises
since: 12.1.0
---

The `all` function is similar to the builtin Promise.all or Promise.allSettled
functions. Given a list (or object) of promises, if any errors are thrown, all
errors are gathered and thrown in an AggregateError.

### Using an Array

Passing an array as an argument will return the resolved promise values as an array in the same order.

```ts
import * as _ from 'radashi'

const [user] = await _.all([
  api.users.create(...),
  s3.buckets.create(...),
  slack.customerSuccessChannel.sendMessage(...)
])
```

### Using an Object

Passing an object as an argument will return an object with the same keys and the values as the resolved promise values.

```ts
import * as _ from 'radashi'

const { user } = await _.all({
  user: api.users.create(...),
  bucket: s3.buckets.create(...),
  message: slack.customerSuccessChannel.sendMessage(...)
})
```

### Search terms

- Often referred to as `all`, `promiseAll`, or `aggregatePromiseAll`

### Popular use cases

- Use this function to concurrently execute multiple asynchronous tasks, ensuring that all results are gathered, while handling any potential errors in a clean and organized manner.
- Utilize it in a scenario where you need to create multiple resources (e.g., users, buckets, channels) at the same time from different APIs, and want to manage both successful responses and potential errors effectively.
- Leverage it for parallel execution of API calls in a batch process, where each promise may fail independently, but you still want to collect all results or errors related to these calls.
