---
title: tryit
description: Convert a function to an error-first function
since: 12.1.0
---

### Usage

Error-first callbacks were cool. Using mutable variables to hoist state when doing try/catch was not cool.

The `tryit` function let's you wrap a function to convert it to an error-first function. **Works for both async and sync functions.**

```ts twoslash
import * as _ from 'radashi'
// @noErrors

const api = {
  users: {
    find: async (id: number) => id < 3 ? { id, name: 'Alice' } : throw new Error('Not found'),
  },
}
const userIdA = 1
const userIdB = 3

const [errA, userA] = await _.tryit(api.users.find)(userIdA) // [null, { id: 1, name: 'Alice' }]
const [errB, userB] = await _.tryit(api.users.find)(userIdB) // [Error('Not found'), undefined]
```

### Currying

You can curry `tryit` if you like.

```ts twoslash
import * as _ from 'radashi'
// @noErrors

// ---cut-start---
const api = {
  users: {
    find: async (id: number) => id < 3 ? { id, name: 'Alice' } : throw new Error('Not found'),
  },
}

const userId = 1
// ---cut-end---
const findUser = _.tryit(api.users.find)

const [err, user] = await findUser(userId)
```
